"""Motox-specifieke product_type → Shopify taxonomy overlay.

Nederlandse e-bihr / Motox Types verschillen van KTM Engelse PowerParts-types.
Wordt gemerged vóór de gedeelde TYPE_EXACT wanneer shop="motox".
"""

from __future__ import annotations

from modules.category_mapper import (
    AIR_INTAKE,
    BIKE_ACCESSORIES,
    BIKE_HELMETS,
    BIKE_PARTS,
    BOOTS,
    BRAKING,
    CLEANERS,
    CLOTHING,
    CONTROLS,
    COOLING,
    CYCLING_APPAREL,
    DECALS,
    DEFAULT_SHOPIFY_PRODUCT_CATEGORY,
    DRINK_BOTTLES,
    DRIVETRAIN,
    ELECTRICAL,
    ENGINE_PARTS,
    EVENT_MATERIAL,
    EXHAUST,
    FRAME_BODY,
    FUEL,
    GLUE,
    GLOVES,
    GOGGLES,
    HELMETS,
    LIGHTING,
    MIRRORS,
    MOTO_BAGS,
    MOTORCYCLE_OUTERWEAR,
    OIL_CIRC,
    SEATING,
    SENSORS,
    SUSPENSION,
    TOOLS,
    WHEELS,
    WINDOW,
)

# Te vage Motox-bakken → tekst eerst.
GENERIC_TYPES_MOTOX: set[str] = {
    'beschermers',
    'bescherming',
    'big sale off-road & atv',
    'distributie',
    'factory kit',
    'hardware',
    'koppeling',
    'ophanging',
    'opruiming elektriciteit',
    'opruiming motor & uitlaat',
    'opruiming motorkleding & helmen',
    'opruiming plastics & protectie',
    'opruiming rijwielgedeelte',
    'opruiming voertuiguitrusting',
    'plastics',
    'remmen',
    'reserveonderdelen motor',
    'reserveonderdelen rijwielgedeelte',
    'smering',
    'textiel en accessoires',
    'transmissie',
    'transport - garage - paddock',
    '¯\\_(ツ)_/¯',
}

SOFT_TYPE_FALLBACKS_MOTOX: dict[str, str] = {
    'beschermers': FRAME_BODY,
    'bescherming': FRAME_BODY,
    'distributie': ENGINE_PARTS,
    'hardware': FRAME_BODY,
    'koppeling': DRIVETRAIN,
    'ophanging': SUSPENSION,
    'plastics': FRAME_BODY,
    'remmen': BRAKING,
    'smering': OIL_CIRC,
    'transmissie': DRIVETRAIN,
}

# Exacte Motox/e-bihr Types (lowercase keys).
TYPE_EXACT_MOTOX: dict[str, str] = {
    'aandrijfriem beschermer': DRIVETRAIN,
    'aandrijfrubbers': DRIVETRAIN,
    'accessoires handvatten': GLOVES,
    'accessoires spiegel': MIRRORS,
    'accu': ELECTRICAL,
    'acculaders': ELECTRICAL,
    'achterbrug beschermer': FRAME_BODY,
    'achterbrug stickerset': DECALS,
    'achterbruglagers': SUSPENSION,
    'achterlicht origineel': LIGHTING,
    'achterlicht universeel': LIGHTING,
    'achterspatbord': FRAME_BODY,
    'achterspatbordverlengers': FRAME_BODY,
    'achtertandwiel': DRIVETRAIN,
    'adventure helm': HELMETS,
    'afdekking richtingaanwijzergat': LIGHTING,
    'antidiefstal': ELECTRICAL,
    'atv': DEFAULT_SHOPIFY_PRODUCT_CATEGORY,
    'bagage rijder': MOTORCYCLE_OUTERWEAR,
    'bagagedragers en rekken': MOTO_BAGS,
    'balanceertoestellen': TOOLS,
    'balhoofdlagers': SUSPENSION,
    'bandenklem': WHEELS,
    'bandenmachines': TOOLS,
    'bandenwarmers': TOOLS,
    'belgom verzorgingsproducten': CLEANERS,
    'bell culture': HELMETS,
    'bell off-road': HELMETS,
    'bell street': HELMETS,
    'benzinefilters': FUEL,
    'beschermende shorts': MOTORCYCLE_OUTERWEAR,
    'bescherming carter': FRAME_BODY,
    'bescherming ketting': DRIVETRAIN,
    'bescherming koppelingscilinder': DRIVETRAIN,
    'bescherming lateraal': FRAME_BODY,
    'bescherming radiator': COOLING,
    'bescherming schokdemper': SUSPENSION,
    'bescherming tank': FRAME_BODY,
    'bescherming uitlaat': EXHAUST,
    'bescherming voorvork': SUSPENSION,
    'big bore kit': ENGINE_PARTS,
    'big sale off-road & atv': EVENT_MATERIAL,
    'binnenvoering': HELMETS,
    'bobbins achterbrug': FRAME_BODY,
    'bobine': ELECTRICAL,
    'body protectoren': MOTORCYCLE_OUTERWEAR,
    'boren, tappen en matrijzen': TOOLS,
    'borst protectoren': MOTORCYCLE_OUTERWEAR,
    'bougie': ENGINE_PARTS,
    'bougiedop': ELECTRICAL,
    'bougiesleutels': TOOLS,
    'bovenblok pakkingen': ENGINE_PARTS,
    'bovenste motorkit': ENGINE_PARTS,
    'brandstofadditief': OIL_CIRC,
    'brandstofpomp': FUEL,
    'brekers en trekkers': TOOLS,
    'broozer': HELMETS,
    'bullitt carbon': HELMETS,
    'carburateur': FUEL,
    'cardanhoes': FRAME_BODY,
    'carterplug': ENGINE_PARTS,
    'chokekabel': FUEL,
    'cilinder': ENGINE_PARTS,
    'cilinder kit': ENGINE_PARTS,
    'cilinderbus': ENGINE_PARTS,
    'cilinderkop': ENGINE_PARTS,
    'cilinderkop inzetstukken': ENGINE_PARTS,
    'cilinderkoppakking': ENGINE_PARTS,
    'claxon': ELECTRICAL,
    'clip-ons': CONTROLS,
    'collector': EXHAUST,
    'compressiekleding': MOTORCYCLE_OUTERWEAR,
    'compressoren': TOOLS,
    'condensator': ELECTRICAL,
    'connectoren': ELECTRICAL,
    'conversiekits kleppen': ENGINE_PARTS,
    'cover luchtfilterbehuizing': AIR_INTAKE,
    'crossbril accessoires': GOGGLES,
    'crossbrillen': GOGGLES,
    'crosslaarzen': BOOTS,
    'crossshirts': CLOTHING,
    'cruise control': ELECTRICAL,
    'custom 500/500 dlx': HELMETS,
    'decalkit': DECALS,
    'demperrubber koppelingshuis': DRIVETRAIN,
    'dichting schokdemper en stofkap': SUSPENSION,
    'distributie en opslag': ENGINE_PARTS,
    'distributieketting': DRIVETRAIN,
    'doppen en ratels': TOOLS,
    'drijfstang kit': ENGINE_PARTS,
    'drijfstangpen': ENGINE_PARTS,
    'ecu': ELECTRICAL,
    'einddemper': EXHAUST,
    'electrische energie': ELECTRICAL,
    'elektrische haspels': TOOLS,
    'eliminator': HELMETS,
    'eliminator carbon': HELMETS,
    'elleboog protectoren': MOTORCYCLE_OUTERWEAR,
    'enduro jassen': MOTORCYCLE_OUTERWEAR,
    'engelse sleutels': TOOLS,
    'expansie uitlaat': EXHAUST,
    'extra verlichting': LIGHTING,
    'factory kit': ENGINE_PARTS,
    'fiets remmen & shifters': BIKE_PARTS,
    'fietsbroeken': CYCLING_APPAREL,
    'fietshelmen': BIKE_HELMETS,
    'fietsjassen': CYCLING_APPAREL,
    'fietskleding accessoires': CYCLING_APPAREL,
    'fietsschoenen': CYCLING_APPAREL,
    'fietsshirts': CYCLING_APPAREL,
    'filterdeksels': AIR_INTAKE,
    'filterolie': OIL_CIRC,
    'filterreiniger': CLEANERS,
    'filtersleutels': TOOLS,
    'frame inserts': FRAME_BODY,
    'gasbuis': CONTROLS,
    'gashendel kit': CONTROLS,
    'gashendels': CONTROLS,
    'gaskabel': CONTROLS,
    'gasschuif': FUEL,
    'gemengde sleutels': TOOLS,
    'gereedschap voor connectoren': TOOLS,
    'gereedschappen rijwielgedeelte': TOOLS,
    'gereedschapswagens en kasten': TOOLS,
    'gevoerde koppelingsplaat': DRIVETRAIN,
    'glideplate phd': FRAME_BODY,
    'handgereedschap': TOOLS,
    'handkappen': FRAME_BODY,
    'heftafels en accessoires': TOOLS,
    'helicoils en draadbussen': TOOLS,
    'hendelbescherming': FRAME_BODY,
    'hoofdkoppelingcilinder': DRIVETRAIN,
    'hoofdremcilinder': ENGINE_PARTS,
    'hoofdremcilinder deksel': ENGINE_PARTS,
    'houder koppelingshendel': CONTROLS,
    'hydratatie': DRINK_BOTTLES,
    'hydraulische persen': TOOLS,
    'hygiëne & reininger': CLEANERS,
    'inlaatpijp': FUEL,
    'intercom': ELECTRICAL,
    'jerrycans': TOOLS,
    'junior helmen': HELMETS,
    'kabelboom': ELECTRICAL,
    'keerring onderblok': ENGINE_PARTS,
    'keerring uitgaande as': ENGINE_PARTS,
    'kentekenplaathouder': FRAME_BODY,
    'ketting': DRIVETRAIN,
    'kettinggeleider': DRIVETRAIN,
    'kettingkit': DRIVETRAIN,
    'kettingreiniger': CLEANERS,
    'kettingroller': DRIVETRAIN,
    'kettingsmeer': OIL_CIRC,
    'kettingspanner': DRIVETRAIN,
    'kickstarter': CONTROLS,
    'kit cartridge': SUSPENSION,
    'kit gevoerde + stalen koppelingsplaten': DRIVETRAIN,
    'kit gevoerde koppelingsplaten': DRIVETRAIN,
    'kit stalen koppelingsplaten': DRIVETRAIN,
    'kit voorvorkveren': SUSPENSION,
    'kleefproducten en fixaties': GLUE,
    'kleppen': ENGINE_PARTS,
    'klepregeling: shims': ENGINE_PARTS,
    'klepsteeldichtingen': ENGINE_PARTS,
    'knie protectoren': MOTORCYCLE_OUTERWEAR,
    'koelmiddel': OIL_CIRC,
    'koppelingscilinder': DRIVETRAIN,
    'koppelingsdeksel': DRIVETRAIN,
    'koppelingsdeksel pakking': DRIVETRAIN,
    'koppelingsdeksel sticker': DECALS,
    'koppelingshendel': CONTROLS,
    'koppelingshuis pakking': DRIVETRAIN,
    'koppelingskabel': CONTROLS,
    'koppelingsleidingen': DRIVETRAIN,
    'koppelingsveren': DRIVETRAIN,
    'kruipolie': OIL_CIRC,
    'krukas': ENGINE_PARTS,
    'krukas kit': ENGINE_PARTS,
    'krukaskeerring': ENGINE_PARTS,
    'krukaslager': ENGINE_PARTS,
    'kunstof framebescherming': FRAME_BODY,
    'kyb vering reviseren': SUSPENSION,
    'lagerkit versnellingsbak': ENGINE_PARTS,
    'loctite': GLUE,
    'losse onderdelen bediening': CONTROLS,
    'luchtfilterkast': AIR_INTAKE,
    'luchtfilters': AIR_INTAKE,
    'meetintrumenten': TOOLS,
    'meetkunde': TOOLS,
    'membraan systeem': AIR_INTAKE,
    'membraanplaatjes': AIR_INTAKE,
    'merkspecifieke gereedschappen': TOOLS,
    'metrologie': TOOLS,
    'middenbok': FRAME_BODY,
    'milieumatten': TOOLS,
    'modderschraper': FRAME_BODY,
    'momentsleutels': TOOLS,
    'motip': CLEANERS,
    'moto-10 spherical': HELMETS,
    'moto-3': HELMETS,
    'moto-9 mips': HELMETS,
    'moto-9s flex': HELMETS,
    'motordiagnose': ELECTRICAL,
    'motorhelm accessoires en onderdelen': HELMETS,
    'motorhoezen': FRAME_BODY,
    'motorliften': TOOLS,
    'motorolie 2t': OIL_CIRC,
    'motorolie 4t': OIL_CIRC,
    'muc-off verzorgingsproducten': CLEANERS,
    'mutsen & petten': CLOTHING,
    'mx broek': MOTORCYCLE_OUTERWEAR,
    'mx-9 adventure mips': HELMETS,
    'mx-9 mips': HELMETS,
    'naaf': WHEELS,
    'naaldlager': ENGINE_PARTS,
    'neutraalschakelaar': ELECTRICAL,
    'nokkenas': ENGINE_PARTS,
    'nummerbplaat met verlichting': LIGHTING,
    'nummerplaat met verlichting en reserveonderdelen': LIGHTING,
    'nummerplaat stickers': DECALS,
    'off-road grips': GLOVES,
    'off-road handschoenen': GLOVES,
    'off-road helmen': HELMETS,
    'off-road stickerset': DECALS,
    'off-road zadelhoes': SEATING,
    'olie aftappluggen': OIL_CIRC,
    'oliedistributie produkten': OIL_CIRC,
    'onderdelen laarzen': BOOTS,
    'onderhoudsproducten': CLEANERS,
    'onderzetter zijstandaard': FRAME_BODY,
    'ontstekingsdeksel': ENGINE_PARTS,
    'ontstekingsdeksel pakking': ENGINE_PARTS,
    'ontvetter': CLEANERS,
    'opruiming motor & uitlaat': EXHAUST,
    'opruiming motorkleding & helmen': HELMETS,
    'opruiming plastics & protectie': FRAME_BODY,
    'opruiming rijwielgedeelte': FRAME_BODY,
    'opvangbakken en steunen': TOOLS,
    'oversized remschijf': BRAKING,
    'paddockstands': TOOLS,
    'pitbord': EVENT_MATERIAL,
    'plastic kits': FRAME_BODY,
    'pneumatisch': TOOLS,
    'poetsmiddel': CLEANERS,
    'powerflow kits': FUEL,
    'powerflow throttle body kit': FUEL,
    'pro star': HELMETS,
    'promotiemateriaal': EVENT_MATERIAL,
    'qualifier dlx': HELMETS,
    'race star flex dlx': HELMETS,
    'radiateurlamellen / radiateurhoes': COOLING,
    'radiator': COOLING,
    'radiator stickerset': DECALS,
    'radiatorkappen': COOLING,
    'radiatorslangen': COOLING,
    'regenjassen': MOTORCYCLE_OUTERWEAR,
    'reiniger & doekjes': CLEANERS,
    'relais en weerstand': ELECTRICAL,
    'rem- en koppelingsvloeistof': OIL_CIRC,
    'remblokken': BRAKING,
    'remblokken as': BRAKING,
    'remhendel': CONTROLS,
    'remhendel & koppelingshendel': CONTROLS,
    'remkabel': BRAKING,
    'remklauw bouten': BRAKING,
    'remklauw reparatiekit': BRAKING,
    'remklauwen': BRAKING,
    'remleidingen': BRAKING,
    'remlichtschakelaar': BRAKING,
    'remmenreiniger': CLEANERS,
    'rempedaal': CONTROLS,
    'remschijf beschermer': BRAKING,
    'remschijf schroeven': BRAKING,
    'remschijven': BRAKING,
    'remschoenen': BRAKING,
    'reparatie banden en velgen': WHEELS,
    'reparatiekit hoofdremcilinder': ENGINE_PARTS,
    'reparatiekit koppelingsslaafcilinder': DRIVETRAIN,
    'reserveonderdelen bell': HELMETS,
    'reserveonderdelen en accessoires voor fietshelmen': HELMETS,
    'reserveonderdelen handkappen': FRAME_BODY,
    'reserveonderdelen helm': HELMETS,
    'reserveonderdelen motor': ENGINE_PARTS,
    'reserveonderdelen nummerplaat met verlichting': LIGHTING,
    'reserveonderdelen rijwielgedeelte': FRAME_BODY,
    'reserveonderdelen startmotor': ELECTRICAL,
    'revisiekit balans-as': ENGINE_PARTS,
    'revisiekit benzinekraan': FUEL,
    'revisiekit carburateur': FUEL,
    'revisiekit hernemingspomp': FUEL,
    'revisiekit schokdemper': SUSPENSION,
    'revisiekit uitgaande as': ENGINE_PARTS,
    'revisiekit verrijkingspomp': FUEL,
    'revisiekit voorvork': SUSPENSION,
    'revisiekit waterpomp': COOLING,
    'richtingaanwijzer - oe type': LIGHTING,
    'richtingaanwijzer - universele': LIGHTING,
    'ronde remschijven': BRAKING,
    'rotor': ENGINE_PARTS,
    'scherm': WINDOW,
    'schokbreker revisie': SUSPENSION,
    'schokdemper': SUSPENSION,
    'schokdemper olie': OIL_CIRC,
    'schokdemperschort': SUSPENSION,
    'schroeven en moeren': FRAME_BODY,
    'schroevendraaiers': TOOLS,
    'silent blocs': FRAME_BODY,
    'skidplate': FRAME_BODY,
    'slaggereedschappen': TOOLS,
    'slipkoppeling': DRIVETRAIN,
    'snelsluitingen': FRAME_BODY,
    'sokken & onderkleding': CLOTHING,
    'sorteerbakken': TOOLS,
    'spacers': FRAME_BODY,
    'spaken': WHEELS,
    'spanbanden & stuurstroppen': FRAME_BODY,
    'spanningsregelaar': ELECTRICAL,
    'spatbord': FRAME_BODY,
    'spatborden kit': FRAME_BODY,
    'specifieke gereedschappen': TOOLS,
    'spiegel': MIRRORS,
    'spiegel - universele': MIRRORS,
    'spiegel oe type': MIRRORS,
    'spoelbakken': TOOLS,
    'stalen koppelingsplaat': DRIVETRAIN,
    'startblok': TOOLS,
    'startkit': ENGINE_PARTS,
    'startmotor': ELECTRICAL,
    'startonderbreker / killswitch': ELECTRICAL,
    'stator': ELECTRICAL,
    'stickervel': DECALS,
    'stuur': CONTROLS,
    'stuur 22,2 mm': CONTROLS,
    'stuur 28,6 mm': CONTROLS,
    'stuur en achterbrug': FRAME_BODY,
    'stuurbevestiging': CONTROLS,
    'stuurgewichten': CONTROLS,
    'stuurverhogers': CONTROLS,
    'sweatshirts & truien': CLOTHING,
    't- en y-sleutels': TOOLS,
    "t-shirts, polo's & shirts": CLOTHING,
    'tangen': TOOLS,
    'tankdop': FUEL,
    'tenten': EVENT_MATERIAL,
    'testers': TOOLS,
    'textiel en accessoires': CLOTHING,
    'textiele jassen': MOTORCYCLE_OUTERWEAR,
    'thermokleding en reflectievesten': CLOTHING,
    'torx en inbus sleutels': TOOLS,
    'tps sensor': ELECTRICAL,
    'trial handvatten': GLOVES,
    'uitlaat': EXHAUST,
    'uitlaataccessoires': EXHAUST,
    'uitlaatkleppen': EXHAUST,
    'uitlaatpakking': EXHAUST,
    'ultrasoonbakken': TOOLS,
    'veervoorspanningsregelaar': ELECTRICAL,
    'velg onderdelen': WHEELS,
    'velgen voor originele naaf': WHEELS,
    'velgen voor specifieke naaf': WHEELS,
    'velgenreiniger': CLEANERS,
    'ventielen': WHEELS,
    'verf': CLEANERS,
    'verhoging + verlagingssets': SUSPENSION,
    'verlichting': LIGHTING,
    'versnellingsbakolie': OIL_CIRC,
    'vesten & jassen': MOTORCYCLE_OUTERWEAR,
    'vet': OIL_CIRC,
    'vintage handvatten': GLOVES,
    'vintage luchtfilter': AIR_INTAKE,
    'vintage plastics': FRAME_BODY,
    'vizier': HELMETS,
    'vliegwieltrekkers': TOOLS,
    'vlotter': FUEL,
    'vlotternaald': FUEL,
    'voetsteunbevestiging': CONTROLS,
    'voetsteunen': CONTROLS,
    'volledige koppelingshendel': CONTROLS,
    'volledige pakkingsets': ENGINE_PARTS,
    'volledige remhendel': CONTROLS,
    'volledige uitlaatlijn': EXHAUST,
    'voornummerplaat': FRAME_BODY,
    'voorspatbord': FRAME_BODY,
    'voortandwiel': DRIVETRAIN,
    'voorvork': SUSPENSION,
    'voorvork en onderdelen': SUSPENSION,
    'voorvork stickers': DECALS,
    'voorvorkbeschermers': FRAME_BODY,
    'voorvorkbuizen': SUSPENSION,
    'voorvorkkeeringen': SUSPENSION,
    'voorvorkkeerringen + stofkappen': SUSPENSION,
    'vorkolie': OIL_CIRC,
    'waterpompdeksel en propeller': COOLING,
    'wave remschijven': BRAKING,
    'wd-40 verzorgingsproducten': CLEANERS,
    'werkplaatsmachines': TOOLS,
    'werkplaatsmeubilair': TOOLS,
    'werkplaatsuitrusting': TOOLS,
    'wielen': WHEELS,
    'wiellagers': WHEELS,
    'windscherm': WINDOW,
    'zaag- en snijgereedschappen': TOOLS,
    'zachte bagage': MOTO_BAGS,
    'zadel': SEATING,
    'zadelschuim': SEATING,
    'zelfklevende antislip': FRAME_BODY,
    'zijstandaard': FRAME_BODY,
    'zuiger': ENGINE_PARTS,
    'zuigerpen': ENGINE_PARTS,
    'zuigers': ENGINE_PARTS,
    'zuigerveren': ENGINE_PARTS,
    '¯\\_(ツ)_/¯': EVENT_MATERIAL,
    'aansluitbuis': FUEL,
    'achterbruggeleider': FRAME_BODY,
    'afzuigsystemen': TOOLS,
    'bakken, gieters en trechters': TOOLS,
    'binnenklok': SENSORS,
    'carburatie en injectie': FUEL,
    'differentieellagers + afdichtingen': DRIVETRAIN,
    'drukplaat': DRIVETRAIN,
    'electronische diagnose': ELECTRICAL,
    'elektronische diagnose': ELECTRICAL,
    'gordel': MOTORCYCLE_OUTERWEAR,
    'indicator adapter cable': LIGHTING,
    'kabelgeleiders': CONTROLS,
    'kabelkits': CONTROLS,
    'kabelspanners etc.': CONTROLS,
    'korf': DRIVETRAIN,
    'kroonplaat': SUSPENSION,
    'leidingen': BRAKING,
    'oliefilters': OIL_CIRC,
    'onderhoud van leer & textiel': CLEANERS,
    'ontluchtingsventiel': BRAKING,
    'oprijplaten en transport': TOOLS,
    'opruiming elektriciteit': ELECTRICAL,
    'opruiming voertuiguitrusting': DEFAULT_SHOPIFY_PRODUCT_CATEGORY,
    'revisieskit linksysteem': SUSPENSION,
    'sanitaire veiligheid': TOOLS,
    'schakelpook': CONTROLS,
    'schroefbits en verloopstukken': TOOLS,
    'schuurmiddelen': TOOLS,
    'slangen, aansluitingen en filters': FUEL,
    'slangenklemmen': FRAME_BODY,
    'starters': ELECTRICAL,
    'stelschroef': CONTROLS,
    'stofhoes': FRAME_BODY,
    'stofkap': FRAME_BODY,
    'stuurrol': CONTROLS,
    'stuurschakelaar': ELECTRICAL,
    'tellerkabel': SENSORS,
    'transport - garage - paddock': TOOLS,
    'vacuumslangen': FUEL,
    'zijnummerplaten': FRAME_BODY,
}

TYPE_PREFIX_MOTOX: list[tuple[str, str]] = [
    ("fiets", BIKE_ACCESSORIES),
    ("off-road helm", HELMETS),
    ("mx broek", MOTORCYCLE_OUTERWEAR),
    ("reserveonderdelen helm", HELMETS),
]

